### ISSUE TITLE
O co-op começa com o menu aberto

### ISSUE THREAD

**Issue by TheLinceCop** [syl3n7/MyLittleExploree#10]
![imagem](https://user-images.githubusercontent.com/16721058/168452147-cc486393-049a-442e-bf92-c4d2633066c2.png)

Quando se inicia ou reinicia o co-op, o menu fica aberto, o que faz com que para jogar é necessário usar o "esc" por que se usar o "play again" o menu continua aberto.

**Comment by syl3n7** [comment]
https://github.com/syl3n7/MyLittleExploree/commit/288794f87b1285f5f9b695c86157c8ecc1777812
