### ISSUE TITLE
Impossibilidade de saltar

### ISSUE THREAD

**Issue by TheLinceCop** [syl3n7/MyLittleExploree#2]
![imagem](https://user-images.githubusercontent.com/16721058/167507077-8fbad179-1596-4ec8-a47a-0a513dbbc02d.png)

Nessa parte do mapa, a caixa consegue passar por baixo do chão superior, o que faz com que quando se suba nela, ela fique internamente a colidir com o personagem e o chão, fazendo com que não seja possível saltar.

**Comment by syl3n7** [comment]
The scale of this specific Box will have to be changed in order for the bug to be solved.

**Comment by syl3n7** [comment]
Nao consegui reproduzir, tornei a caixa dinamica e agora existe rotacao em Z, por isso deve dar para saltar sempre

**Comment by syl3n7** [comment]
https://github.com/syl3n7/MyLittleExploree/commit/288794f87b1285f5f9b695c86157c8ecc1777812
