### ISSUE TITLE
Deixou de dar para saltar na pedra

### ISSUE THREAD

**Issue by TheLinceCop** [syl3n7/MyLittleExploree#9]
![imagem](https://user-images.githubusercontent.com/16721058/168451937-ec6f8fc2-b59f-45bf-9f55-1ddb1cc43be0.png)

Na parte que é preciso subir na pedra para saltar para a próxima terra, deixou de dar para saltar.

**Comment by syl3n7** [comment]
https://github.com/syl3n7/MyLittleExploree/commit/288794f87b1285f5f9b695c86157c8ecc1777812
